---
name: CI-forgejo-cli
'on':
  workflow_dispatch:
  pull_request:

jobs:
  molecule:
    name: Molecule
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro:
          - ubuntu2404
          # - debian12

    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v4

      - name: Install mise
        uses: jdx/mise-action@v2
        with:
          install: true
          cache: true

      - name: Install Python deps
        run: mise run install-deps

      - name: Run Molecule tests.
        run: mise exec -- molecule test -s forgejo-cli
        env:
          FORGEJO_TOKEN: ${{ secrets.FORGEJO_TOKEN }}
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}
